"""Newsletter Generator Workflow. Demonstrates parallel multi-section drafting."""

from typing import Any
from src.agentframework.workflow import WorkflowGraph
import streamlit as st

def get_workflow() -> WorkflowGraph:
    """Return the configured pipeline template."""
    graph = WorkflowGraph()

    async def start(state: dict[str, Any]) -> dict[str, Any]:
        """Entry point setting up the context payload."""
        state["subject"] = state.get("topic", "Technology News")
        return state

    async def draft_intro(state: dict[str, Any]) -> dict[str, Any]:
        """Parallel Branch: Introduction."""
        res = await st.session_state.agent.run(
            f"Write a catchy 3-sentence introduction for a newsletter about {state['subject']}."
        )
        state["intro"] = res
        return state

    async def draft_body(state: dict[str, Any]) -> dict[str, Any]:
        """Parallel Branch: Main Body."""
        res = await st.session_state.agent.run(
            f"Write two informative paragraphs detailing recent trends and news concerning {state['subject']}."
        )
        state["body"] = res
        return state

    async def draft_conclusion(state: dict[str, Any]) -> dict[str, Any]:
        """Parallel Branch: Conclusion."""
        res = await st.session_state.agent.run(
            f"Write a 2-sentence concluding thought wrapping up a newsletter on {state['subject']}."
        )
        state["conclusion"] = res
        return state

    def reducer(states: list[dict[str, Any]]) -> dict[str, Any]:
        """Merge drafted sections."""
        merged = states[0].copy()
        for s in states[1:]:
            merged.update(s)
        return merged

    async def format_newsletter(state: dict[str, Any]) -> dict[str, Any]:
        """Final output formatter applying Markdown syntax."""
        state["final"] = (
            f"## 📰 The {state['subject'].title()} Weekly\n\n"
            f"{state.get('intro', '')}\n\n"
            f"---\n\n"
            f"{state.get('body', '')}\n\n"
            f"---\n\n"
            f"{state.get('conclusion', '')}\n\n"
            f"*(Autogenerated via Echo AI Orchestrator)*"
        )
        return state

    # Build Graph Topology
    graph.add_node("start", start)
    graph.add_node("draft_intro", draft_intro)
    graph.add_node("draft_body", draft_body)
    graph.add_node("draft_conclusion", draft_conclusion)
    graph.add_node("format_newsletter", format_newsletter)
    
    # Define route map
    graph.set_entry_point("start")
    
    graph.add_parallel_edge(
        source="start", 
        targets=["draft_intro", "draft_body", "draft_conclusion"], 
        reducer=reducer, 
        next_node="format_newsletter"
    )
    
    graph.add_edge("format_newsletter", graph.END)
    
    return graph
