# cargo-deny configuration. Run via `cargo deny check` in CI (AGENTS.md
# "Static analysis"): advisory DB scan, license check, duplicate-dependency
# check. Treating multiple versions as a deny matches the C repo's
# duplicate-dependency gate — duplicates get resolved, not allowed.
[advisories]
yanked = "deny"
version = 2

[bans]
multiple-versions = "deny"

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "ISC",
    "Zlib",
    "Unicode-3.0",
    "CC0-1.0",
    "MPL-2.0",
    "0BSD",
]