//! Session model: a conversation's identity, messages, metadata, and
//! events, plus the JSON serialization used by the encrypted store.
//!
//! `metadata` and `events` are kept as generic `serde_json::Value` — the
//! branch/tag bookkeeping (Phase 4/5) and event logging evolve freely
//! without churning this module's API. `messages` use the
//! C-compatible [`crate::agent::message::Message`] shape.
//!
//! Submodules: `db` (schema), `encryption` (Fernet/scrypt vault),
//! `manager` (the facade), `memory` (user facts), `migration`
//! (crash-safe password change). `serialize`/`list`/`purge`/`branch`
//! from the C project live inside the manager here — the split the C
//! version needed for file-length discipline is handled by Rust's
//! module system without extra files.
//!
//! Depends on: `serde_json`, `rusqlite`, crate `agent::message`.

use crate::agent::message::Message;

pub mod db;
pub mod encryption;
pub mod manager;
pub mod memory;
pub mod migration;

pub use manager::SessionManager;

/// A persisted conversation.
#[derive(Debug, Clone, Default)]
pub struct Session {
    /// Unique id (hex string, generated by the manager).
    pub id: String,
    /// Decrypted title; `None` until generated or set.
    pub title: Option<String>,
    /// Whether a title-generation attempt already happened (prevents
    /// retry loops in the C version's flow).
    pub title_generation_attempted: bool,
    /// Creation timestamp as stored in the DB (ISO-8601 text).
    pub created_at: String,
    /// The conversation.
    pub messages: Vec<Message>,
    /// Free-form metadata object (branching bookkeeping, tags, ...).
    pub metadata: serde_json::Value,
    /// Ordered event log (JSON objects).
    pub events: Vec<serde_json::Value>,
}

impl Session {
    /// Creates an empty session with the given id and a fresh creation
    /// timestamp.
    pub fn new(id: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            title: None,
            title_generation_attempted: false,
            created_at: now_iso(),
            messages: Vec::new(),
            metadata: serde_json::json!({}),
            events: Vec::new(),
        }
    }

    /// Serializes `messages` to JSON text for encryption.
    ///
    /// # Errors
    /// `serde_json` failure on serialization (cannot occur for the
    /// `Message` type; kept for interface completeness).
    pub fn messages_json(&self) -> serde_json::Result<String> {
        serde_json::to_string(&self.messages)
    }

    /// Deserializes messages from JSON text.
    ///
    /// # Errors
    /// `serde_json` failure on malformed input.
    pub fn messages_from_json(json: &str) -> serde_json::Result<Vec<Message>> {
        serde_json::from_str(json)
    }
}

/// ISO-8601-ish timestamp (the C version stored `time(NULL)`-derived
/// text via `ctime`/`asctime`-style formatting; the exact string is not
/// part of any compat contract, only its presence).
fn now_iso() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    match SystemTime::now().duration_since(UNIX_EPOCH) {
        Ok(d) => format!("{}", d.as_secs()),
        Err(_) => String::from("0"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn session_messages_roundtrip() {
        let mut s = Session::new("abc");
        s.messages.push(Message::user("hi"));
        s.messages.push(Message::assistant("hello"));
        let json = s.messages_json().expect("serialize");
        let back = Session::messages_from_json(&json).expect("deserialize");
        assert_eq!(back, s.messages);
    }

    #[test]
    fn empty_session_has_metadata_object() {
        let s = Session::new("x");
        assert!(s.metadata.is_object());
        assert!(s.events.is_empty());
    }
}
