[package]
name = "echo-ai"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "echo-ai"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
echo-ai-server = { path = "../echo-ai-server" }
tokio = { version = "1", features = ["full"] }
echo-ai-core = { path = "../echo-ai-core" }